# Alternative GNU Make workspace makefile autogenerated by Premake

ifndef config
  config=debug
endif

ifndef verbose
  SILENT = @
endif

ifeq ($(config),debug)
  test_project_config = debug

else ifeq ($(config),release)
  test_project_config = release

else
  $(error "invalid configuration $(config)")
endif

PROJECTS := test_project

.PHONY: all clean help $(PROJECTS) 

all: $(PROJECTS)

test_project:
ifneq (,$(test_project_config))
	@echo "==== Building test_project ($(test_project_config)) ===="
	@${MAKE} --no-print-directory -C metadata/project_files -f Makefile config=$(test_project_config)
endif

clean:
	@${MAKE} --no-print-directory -C metadata/project_files -f Makefile clean

help:
	@echo "Usage: make [config=name] [target]"
	@echo ""
	@echo "CONFIGURATIONS:"
	@echo "  debug"
	@echo "  release"
	@echo ""
	@echo "TARGETS:"
	@echo "   all (default)"
	@echo "   clean"
	@echo "   test_project"
	@echo ""
	@echo "For more information, see https://github.com/premake/premake-core/wiki"