editor_camera:
  m_camera_pos: 17.7871 4.78857 9.53937
  m_camera_direction: 0.240186 5.2632 0
  m_move_speed: 34,000000
windows_to_show:
  show_main_menu_bar: false
  show_options: false
  show_graphics_engine_settings: false
  show_editor_settings: false
  show_general_settings: false
  show_engine_wiki: false
  show_todo_lis: false
guizmo_data:
  operation: 7
world_viewport_windows_to_show:
  show_renderer_backgrond_effect: false
  show_general_debugger: false
  show_outliner: true
  show_details: true
  show_world_settings: false
