editor_camera:
  m_camera_pos: -0.105074 0.252247 -5.7085
  m_camera_direction: -0.435991 -22.4118 0
  m_move_speed: 2.489029
windows_to_show:
  show_main_menu_bar: false
  show_options: false
  show_graphics_engine_settings: false
  show_editor_settings: false
  show_general_settings: true
  show_engine_wiki: false
  show_style_editor: false
  show_demo_window: false
  show_todo_lis: false
world_viewport_windows_to_show:
  show_renderer_backgrond_effect: true
  show_general_debugger: false
  show_outliner: true
  show_details: true
  show_log_display: false
  show_world_settings: false
world_vieport_data:
  selected_entity: 6196167870948812970
guizmo_data:
  operation: 7
