editor_camera:
  m_camera_pos: 25.8164 146.297 -304.634
  m_camera_direction: 0.739001 3.20035 0
  m_move_speed: 105.743103
windows_to_show:
  show_main_menu_bar: false
  show_options: false
  show_graphics_engine_settings: false
  show_editor_settings: false
  show_general_settings: false
  show_engine_wiki: false
  show_style_editor: false
  show_demo_window: false
  show_todo_lis: false
world_viewport_windows_to_show:
  show_renderer_backgrond_effect: false
  show_general_debugger: false
  show_outliner: true
  show_details: true
  show_world_settings: false
world_vieport_data:
  selected_entity: 4164406557105595165
guizmo_data:
  operation: 7
