script_components:
  file_header:
    version: 1 0 0
    type: 2
    timestamp: 2024 9 9 1 22 48 50 154
  entities:
  - tag: procedural_script_test
    ID: 7072220998543679919
    procedural_mesh_component:
      script_name: test_project::tree_generator
      mobility: 0
      shoudl_render: true
      trunk:
        trunk_direction: 0 1 0
        trunk_length: 50.000000
        trunk_size: 1.000000
      data:
        max_depth: 5
